
INSERT INTO team (abbreviation, market, mascot)
VALUES
  ('ARI', 'Arizona', 'Cardinals'),
  ('ATL', 'Atlanta', 'Falcons'),
  ('BAL', 'Baltimore', 'Ravens'),
  ('BUF', 'Buffalo', 'Bills'),
  ('CAR', 'Carolina', 'Panthers'),
  ('CHI', 'Chicago', 'Bears'),
  ('CIN', 'Cincinnati', 'Bengals'),
  ('CLE', 'Cleveland', 'Browns'),
  ('DAL', 'Dallas', 'Cowboys'),
  ('DEN', 'Denver', 'Broncos'),
  ('DET', 'Detroit', 'Lions'),
  ('GB', 'Green Bay', 'Packers'),
  ('HOU', 'Houston', 'Texans'),
  ('IND', 'Indianapolis', 'Colts'),
  ('JAX', 'Jacksonville', 'Jaguars'),
  ('KC', 'Kansas City', 'Chiefs'),
  ('OAK', 'Oakland', 'Raiders'),
  ('LAM', 'Los Angeles', 'Rams'),
  ('MIA', 'Miami', 'Dolphins'),
  ('MIN', 'Minnesota', 'Vikings'),
  ('NE', 'New England', 'Patriots'),
  ('NO', 'New Orleans', 'Saints'),
  ('NYG', 'New York', 'Giants'),
  ('NYJ', 'New York', 'Jets'),
  ('PHI', 'Philadelphia', 'Eagles'),
  ('PIT', 'Pittsburgh', 'Steelers'),
  ('SD', 'San Diego', 'Chargers'),
  ('SEA', 'Seattle', 'Seahawks'),
  ('SF', 'San Fransisco', '49ers'),
  ('TB', 'Tampa Bay', 'Buccaneers'),
  ('TEN', 'Tennessee', 'Titans'),
  ('WAS', 'Washington', 'Redskins');